Feat/create teams
platanus/lacatan pull request #12
Opened 2021-08-17 22:52 UTC by castrocami

### Contexto
Reconstruyendo Lakatan. En este [pitch](https://www.notion.so/platanus/Interfaz-de-equipos-v1-0-1c4cd55247ce4ec5b0d94dad66cc294a), que corresponde a CRUDs de equipos

### Qué se esta haciendo
​-Crear un modal con un form para poder crear un nuevo team
-Crear un método para enviar un POST request a la API de crear team
-Configurar inline svg package
-Añadir una línea en el controlador para evitar el error "InvalidAuthenticityToken"

#### En particular hay que revisar
​
-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)
<img width="1268" alt="Captura de Pantalla 2021-08-17 a la(s) 6 45 00 p  m" src="https://user-images.githubusercontent.com/69872162/129810466-011072d5-c154-4b62-a940-4cfaa4a14993.png">

2021-08-18 15:14 UTC, gmq requested changes

2021-08-18 15:14 UTC, gmq commented on app/javascript/components/teams/teams-form-modal.vue
> +      const container = document.querySelector('.modal-container');
Esto lo haría dentro de Vue en vez de usar queries de elementos, usando [class bindings](https://vuejs.org/v2/guide/class-and-style.html)

Puedes tener dos [computed](https://vuejs.org/v2/guide/computed.html) con las clases correspondientes para el modal y para modal-container con un condicional adentro que dependa de una variable en data que se actualice en `toggleModal`.

2021-08-18 15:14 UTC, gmq commented on app/javascript/components/teams/teams-form-modal.vue
> +      TeamsApi
Sería ideal tener un loading para mostrar que está pasando algo mientras se hace el request.

2021-08-18 15:14 UTC, gmq commented on app/javascript/components/teams/teams-form-modal.vue
> +    refreshTeams: { type: Function, required: true },
Pasar funciones como props no es taaaan bien visto en el mundo Vue (vs React que es la buena práctica). Lo ideal sería usar eventos acá (si no se está usando vuex), que `sendTeamToApi` haga un `$emit` cuando y que el componente padre [reciba ese evento y haga el refresh](https://vuejs.org/v2/guide/components-custom-events.html).

2021-08-18 19:42 UTC, gmq commented on app/javascript/components/teams/teams-form-modal.vue
> +    class="modal-container"
Sacaría todas las clases que no se están usando (modal-container, modal, etc)

2021-08-18 19:42 UTC, gmq commented on app/javascript/components/teams/teams-form-modal.vue
> +          this.loading = false;
Falta un `catch` para manejar el caso que el servidor tire un error. En estos momentos si hay un error el usuario no va a poder reintentar porque le va a salir el gráfico de loading

2021-08-18 19:42 UTC, gmq commented on app/javascript/components/teams/teams-form-modal.vue
> +import Loading from '../shared/loading.vue';
`Loading` está como componente global, no es necesario importarlo acá.

2021-08-18 19:42 UTC, gmq commented on app/javascript/components/shared/loading.vue
> +<template>
😮 pensé que no se podía hacer un `.vue` sin un `<script>`

2021-08-18 22:00 UTC, castrocami commented on app/javascript/components/teams/teams-form-modal.vue
> +          this.loading = false;
Memo, en el catch solo saco el loading para que el usuario pueda volver a intentar o también hago algo con el mensaje de error?

2021-08-19 15:45 UTC, gmq approved these changes

2021-08-19 15:47 UTC, merged