Feat/edit profile
platanus/lacatan pull request #146
Opened 2022-05-03 18:18 UTC by tamaralues

### Contexto
Se esta implementando el diseño de Lakatan. 
​
### Qué se esta haciendo
En este pr se esta implementando el diseño de la vista para editar el perfil de un usuario. Este cuenta con dos secciones. La primero es la de los datos estándar (todo usuario los tienes) y la sección de atributos dinámicos  ​los cuales son configurados en cada organizaciones. Estos atributos pueden ser de varios tipos: texto, toggle, select, fechas o numeros.

#### En particular hay que revisar
En particular hay que revisar los archivos:  edit.vue, lacatan-input.vue, lacatan-select.vue y toggle-btn.vue, que son los que tienen la lógica principal para el formulario de editar perfil. Adicionalmente se hicieron cambios en el tailwind.config.js, edit.html.erb y application.html.erb, pero son cambios chicos orientados a diseño.
<img width="921" alt="Screen Shot 2022-05-03 at 14 04 53" src="https://user-images.githubusercontent.com/29900907/166517074-fcf5cdb3-cecc-479c-aa48-632cca670bcc.png">
<img width="943" alt="Screen Shot 2022-05-03 at 14 05 21" src="https://user-images.githubusercontent.com/29900907/166517078-5c854f92-9e08-46d7-bbeb-d3e2fa495937.png">
<img width="760" alt="Screen Shot 2022-05-03 at 14 05 31" src="https://user-images.githubusercontent.com/29900907/166517079-dde092a7-a37f-4852-9777-16509cac8bb3.png">

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)
<img width="700" alt="Screen Shot 2022-05-03 at 14 04 47" src="https://user-images.githubusercontent.com/29900907/166517068-176911f2-e5c1-4a77-a1ab-b62a83525581.png">
<img width="700" alt="Screen Shot 2022-05-03 at 14 04 53" src="https://user-images.githubusercontent.com/29900907/166517074-fcf5cdb3-cecc-479c-aa48-632cca670bcc.png">
<img width="700" alt="Screen Shot 2022-05-03 at 14 05 21" src="https://user-images.githubusercontent.com/29900907/166517078-5c854f92-9e08-46d7-bbeb-d3e2fa495937.png">
<img width="700" alt="Screen Shot 2022-05-03 at 14 05 31" src="https://user-images.githubusercontent.com/29900907/166517079-dde092a7-a37f-4852-9777-16509cac8bb3.png">

2022-05-05 21:57 UTC, difernandez requested changes

2022-05-05 21:57 UTC, difernandez commented on app/javascript/components/shared/lacatan-select.vue
> +        <template v-for="choice in attribute.details.options">
acá puedes poner el `v-for` directo en el `<option>` de abajo, sin necesitar el `template`. El template es necesario si, por ejemplo, quieres iterar sobre algo pero el resultado de esa iteración es más de un elemento por iteración

2022-05-05 21:57 UTC, difernandez commented on app/javascript/components/shared/lacatan-select.vue
> +      default: '',
Si la prop tiene un default, no es necesario setear el `required: false` también

2022-05-05 21:57 UTC, difernandez commented on app/javascript/components/profile/edit.vue
> +    >
veo que estaba así de antes, pero me parece que este input, en vez de tener `absolute max-w-0 max-h-0` debería tener `hidden`. Además, lo pondría justo después de su label para que sea obvia la conexión

2022-05-05 21:57 UTC, difernandez commented on app/javascript/components/profile/edit.vue
> +                  :attribute="attr"
por lo que veo `toggle-button` no recibe un `attribute` de prop

2022-05-05 21:57 UTC, difernandez commented on app/javascript/components/profile/edit.vue
> +      ref="observer"
este `ref` no se usa creo

2022-05-05 21:57 UTC, difernandez commented on app/javascript/components/shared/lacatan-select.vue
> +    },
Me parece que sería bueno no depender de un `atribute`. Como está ahora, el select queda muy atado a la estrucutra de los atributos dinámicos y no se podría usar para otras cosas (o se corre el riesgo de que algo na que ver se trate de adaptar a esta estructura). Creo que se debería pedir las distintas cosas que se necesiten por separado, parecido al `lacatan-input` por lo que veo. Qué opinas?

2022-05-20 15:35 UTC, tamaralues commented on app/javascript/components/shared/lacatan-select.vue
> +    },
Si te encuentro toda la razon! lo cambio!

2022-05-20 17:10 UTC, tamaralues commented on app/javascript/components/shared/lacatan-select.vue
> +        <template v-for="choice in attribute.details.options">
👌

2022-05-20 17:10 UTC, tamaralues commented on app/javascript/components/shared/lacatan-select.vue
> +      default: '',
veldad!

2022-05-20 17:10 UTC, tamaralues commented on app/javascript/components/profile/edit.vue
> +    >
cambiado!

2022-05-20 17:24 UTC, difernandez approved these changes

2022-05-20 17:24 UTC, difernandez commented on app/javascript/components/shared/lacatan-select.vue
> +    },
faltó borrar esta prop no más, que ya no se usa

2022-05-20 17:53 UTC, merged