Feat/update team
platanus/lacatan pull request #15
Opened 2021-08-19 21:34 UTC by castrocami

### Contexto
Reconstruyendo Lakatan. En este [pitch](https://www.notion.so/platanus/Interfaz-de-equipos-v1-0-1c4cd55247ce4ec5b0d94dad66cc294a)  que corresponde a CRUDs de equipos

### Qué se esta haciendo
-Crear vista que contiene los detalles de un team (Por ahora solo nombre y detalles).
-Crear un botón que permita editar la información del team, dirige a un modal.
​
#### En particular hay que revisar
​

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)
<img width="1237" alt="Captura de Pantalla 2021-08-19 a la(s) 5 29 17 p  m" src="https://user-images.githubusercontent.com/69872162/130147047-54e0fd2a-8c77-4883-9218-fa939426c6af.png">
<img width="872" alt="Captura de Pantalla 2021-08-19 a la(s) 5 31 33 p  m" src="https://user-images.githubusercontent.com/69872162/130147080-fd1beeb1-3343-449d-9194-d1aa542e2c68.png">

2021-08-19 22:33 UTC, castrocami commented
![](https://github.trello.services/images/mini-trello-icon.png) [Editar equipo](https://trello.com/c/xZxb9SGs/22-editar-equipo)

2021-08-20 13:37 UTC, aamatte commented on app/javascript/components/teams/teams-form-modal.vue
> +      }
te recomiendo dejarlo como

```
if (this.team) {
   // el update
} else {
  // el create
}
```

2021-08-20 13:39 UTC, aamatte commented on app/javascript/components/teams/teams-form-modal.vue
> +      teamName: this.team ? this.team.name : null,
si es que haces `this.team && this.team.name` obtienes el mismo resultado!
(si el primer elemento de la condición es `null`, lo retorna), y si no, retorna el siguiente.

2021-08-20 13:39 UTC, aamatte commented on app/views/teams/show.html.erb
> +>
este hay que cerrarlo con `</team-details>`

2021-08-20 13:39 UTC, aamatte requested changes
Dejé unos comentarios muy chicos, pero super!

2021-08-20 14:25 UTC, castrocami commented on app/javascript/components/teams/teams-form-modal.vue
> +      teamName: this.team ? this.team.name : null,
uuuu Bacánn

2021-08-20 14:44 UTC, monkeyci commented on app/javascript/components/teams/team-details.vue
> +    }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing semicolon                              semi

2021-08-20 14:44 UTC, monkeyci commented on app/javascript/components/teams/team-details.vue
> +    }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing trailing comma                         comma-dangle

2021-08-20 14:44 UTC, monkeyci commented on app/javascript/components/teams/team-details.vue
> +  }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing trailing comma                         comma-dangle

2021-08-20 14:44 UTC, monkeyci commented on app/javascript/components/teams/team-details.vue
> +</script>
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Newline required at end of file but not found  eol-last

2021-08-20 20:44 UTC, aamatte approved these changes

2021-08-20 21:19 UTC, merged