Feat/add team members
platanus/lacatan pull request #23
Opened 2021-09-02 14:49 UTC by castrocami

### Contexto
Reconstruyendo Lakatan. En este [pitch](https://www.notion.so/platanus/Interfaz-de-equipos-v2-0-5d5e4babe8bc437c94e5a181a188f6de) que corresponde a la creación de una forma en que los integrantes de una organización puedan entrar y salirse de un equipo y además de llevar registro de los miembros de los equipos
​
### Qué se esta haciendo
-Crear componente que permita añadir/editar miembros en un team
-Componente esta dentro del  formulario de equipo, que es utilizado para crear un nuevo team o editar
​
#### En particular hay que revisar
​

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)
<img width="405" alt="Captura de Pantalla 2021-09-02 a la(s) 10 45 36 a  m" src="https://user-images.githubusercontent.com/69872162/131864991-4fc7c039-42c4-4adb-a7d6-2d724a8f23fc.png">

2021-09-03 13:54 UTC, difernandez requested changes

2021-09-03 13:54 UTC, difernandez commented on app/javascript/components/teams/teams-form-modal.vue
> +    },
Esta transformación del usuario a estos tres atributos quizás hace más sentido tenerlo directo en el componente `team-members-selector`, ya que estea más relacionado a lo que se muestra ahí. Onda que acá en este componente se le mande los users tal como son y que el selector se encargue de sacar lo que se necesite para mostrar. Qué opinas?

2021-09-03 13:54 UTC, difernandez commented on app/javascript/components/teams/teams-form-modal.vue
> +                  @selectionMembersChange="setSelectedTeamMembers"
Cuando se tiene este "patrón" de que un componente recibe una prop y tiene un evento para actualizar el valor de esta, se puede hacer que el componente funcione con `v-model` en este caso, pasaría de:
```
:selected-team-members="selectedTeamMembers"
@selectionMembersChange="setSelectedTeamMembers"
```
a:
```
v-model="selectedTeamMembers"
```
Para que esto funcione, se debe cambiar el nombre de la prop a `:value` y el evento que se emite debe ser `@input`. [Acá los docs sobre esto](https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components)

2021-09-03 14:48 UTC, castrocami commented on app/javascript/components/teams/teams-form-modal.vue
> +    },
Si me parece!

2021-09-03 20:53 UTC, castrocami commented
![](https://github.trello.services/images/mini-trello-icon.png) [Crear componente con filtro de miembros de un equipo](https://trello.com/c/0LZ0H7IP/37-crear-componente-con-filtro-de-miembros-de-un-equipo)

2021-09-06 14:06 UTC, difernandez approved these changes
se ve bien! 👍

2021-09-06 14:54 UTC, merged