Dynamic attributes
platanus/lacatan pull request #28
Opened 2021-09-13 13:47 UTC by Tvergara

### Contexto

Sigo trabajando en el pitch de atributos dinámicos de una organización.

[pitch](https://www.notion.so/platanus/Atributos-din-micos-d7daf2e96d15404aba3b17ea5b75971b])
### Qué se esta haciendo

Ya se hizo el PR del backend y ahora ya pase al front. En particular estoy siguiendo lo definido en el [figma](https://www.figma.com/file/X4r28jaYjgjQcRX03aIzd6/Lacatan?node-id=520%3A5147) para la vista de la configuración de una organización.
​
#### En particular hay que revisar
​
La vista creada para la configuración, la cual tiene 3 componentes: el componente base (la configuración) , el modal de crear un atributo, y el modal de eliminar un atributo.

En el futuro habrá un pitch de Lacatan dedicado al diseño, por lo cual hay algunos detalles que no seguí fielmente del figma (como los íconos elegidos).

Las vistas todavía no están conectadas a ninguna lógica del back, ningún botón de crear ni eliminar lleva a nada todavía.

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

(porfa hacemelo $%&#, que es mi primer PR totalmente de front y quiero aprender)

Vistas creadas
![image](https://user-images.githubusercontent.com/58240958/133094297-bc951cc6-71b4-4e9d-9c37-a655ba837957.png)
![image](https://user-images.githubusercontent.com/58240958/133094384-fb49dbf1-ac26-4352-87e2-7b545b5c30f1.png)
![image](https://user-images.githubusercontent.com/58240958/133094446-a128e72f-37fb-4a8d-ace3-8399d37f5191.png)

Vistas del Figma
![image](https://user-images.githubusercontent.com/58240958/133094707-0b26b071-09f6-4fcd-af79-09048cf112a0.png)
![image](https://user-images.githubusercontent.com/58240958/133094763-ebedd825-0b84-47dd-99e7-37176310c7f8.png)

2021-09-13 13:56 UTC, monkeyci commented on spec/engines/dynattributes/models/dynattributes/definition_spec.rb
> +        let(:details) { { type: 'string', name: 'name', label: nil, default: nil, required: false } }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/LineLength: Line is too long. [101/100]

2021-09-13 13:56 UTC, monkeyci commented on spec/engines/dynattributes/models/dynattributes/definition_spec.rb
> +        let(:details) { { type: 'string', name: 'name', label: 'label', default: 1, required: false } }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/LineLength: Line is too long. [103/100]

2021-09-13 13:56 UTC, monkeyci commented on app/javascript/components/organizations/attribute-form-modal.vue
> +                  <option disabled selected hidden>Placeholder</option>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'selected' should be on a new line                                                vue/max-attributes-per-line

2021-09-13 13:56 UTC, monkeyci commented on app/javascript/components/organizations/attribute-form-modal.vue
> +                  <option disabled selected hidden>Placeholder</option>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'hidden' should be on a new line                                                  vue/max-attributes-per-line

2021-09-13 13:56 UTC, monkeyci commented on app/javascript/components/organizations/attribute-form-modal.vue
> +                  <option disabled selected hidden>Placeholder</option>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 line break after opening tag (`<option>`), but no line breaks found    vue/singleline-html-element-content-newline

2021-09-13 13:56 UTC, monkeyci commented on app/javascript/components/organizations/attribute-form-modal.vue
> +                  <option disabled selected hidden>Placeholder</option>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 line break before closing tag (`</option>`), but no line breaks found  vue/singleline-html-element-content-newline

2021-09-13 13:56 UTC, monkeyci commented on app/javascript/components/organizations/attribute-form-modal.vue
> +                  <option value="integer">Número</option>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 line break after opening tag (`<option>`), but no line breaks found    vue/singleline-html-element-content-newline

2021-09-13 13:56 UTC, monkeyci commented on app/javascript/components/organizations/attribute-form-modal.vue
> +                  <option value="integer">Número</option>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 line break before closing tag (`</option>`), but no line breaks found  vue/singleline-html-element-content-newline

2021-09-13 13:56 UTC, monkeyci commented on app/javascript/components/organizations/attribute-form-modal.vue
> +                  <option value="string">Texto</option>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 line break after opening tag (`<option>`), but no line breaks found    vue/singleline-html-element-content-newline

2021-09-13 13:56 UTC, monkeyci commented on app/javascript/components/organizations/attribute-form-modal.vue
> +                  <option value="string">Texto</option>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 line break before closing tag (`</option>`), but no line breaks found  vue/singleline-html-element-content-newline

2021-09-13 13:56 UTC, monkeyci commented on app/javascript/components/organizations/attribute-form-modal.vue
> +                  <option value="date">Fecha</option>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 line break after opening tag (`<option>`), but no line breaks found    vue/singleline-html-element-content-newline

2021-09-13 13:56 UTC, monkeyci commented on app/javascript/components/organizations/attribute-form-modal.vue
> +                  <option value="date">Fecha</option>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 line break before closing tag (`</option>`), but no line breaks found  vue/singleline-html-element-content-newline

2021-09-13 13:56 UTC, monkeyci commented on app/javascript/components/organizations/attribute-form-modal.vue
> +                class="w-2/3 text-center text-white bg-blue-600 p-3 rounded-full">
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 line break before closing bracket, but no line breaks found            vue/html-closing-bracket-newline

2021-09-13 13:56 UTC, monkeyci commented on app/javascript/components/organizations/configuration.vue
> +
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>More than 1 blank line not allowed  no-multiple-empty-lines

2021-09-14 18:55 UTC, difernandez requested changes
Algunos detalles chicos. Y otro comentario: por ahora está bien como está, pero después quizás les convenga sacar el botón que abre un modal del componente mismo del modal. Esto porque puede pasar que tengas más de un lugar que active un modal, y quieras que el botón se vea distinto en ambos lugares (por ejemplo, botón de eliminar como parte de las acciones de cada fila de una tabla o como acción en el show de un elemento). Para eso tendrías que manejar el estado de abierto/cerrado con props/eventos

2021-09-14 18:55 UTC, difernandez commented on engines/dynattributes/app/commands/dynattributes/validate_attribute.rb
>      return 'value must match with type' unless @data['value'].nil? || validate_value_type
Acá si la data es no requerida, y el `value` en nulo, igual se va a tirar un error en la validación de tipo, está bien así?

2021-09-14 18:55 UTC, difernandez commented on app/javascript/components/organizations/configuration.vue
> +            :attr="attr"
esto no se bien que hace, creo que no es necesario, o si?

2021-09-14 18:55 UTC, difernandez commented on app/javascript/components/organizations/configuration.vue
> +            <th class=" px-2 py-2 text-xs font-medium text-gray-900 text-center rounded-tr">
sobra un espacio acá

2021-09-14 18:55 UTC, difernandez commented on app/javascript/components/organizations/configuration.vue
> +            <th class="px-6 py-2 text-xs font-medium text-gray-900  text-left">
:toc: hay un doble espacio "text-gray-900  text-left"

2021-09-14 18:55 UTC, difernandez commented on app/javascript/components/organizations/attribute-form-modal.vue
> +        @click="toggleModal()"
El click mejor ponerlo en el button, que te indica ya el elemento clickeable

2021-09-14 18:55 UTC, difernandez commented on app/javascript/components/organizations/attribute-form-modal.vue
> +                  </option>
Para que esto?

2021-09-14 18:55 UTC, difernandez commented on app/javascript/components/organizations/attribute-form-modal.vue
> +      this.error = false;
error no está definido

2021-09-14 18:55 UTC, difernandez commented on app/javascript/components/organizations/attribute-delete-modal.vue
> +        @click="toggleModal()"
idem @click en el button

2021-09-14 18:55 UTC, difernandez commented on app/javascript/components/organizations/attribute-delete-modal.vue
> +              Esta acción es irreversible y los valores ingresador por los participantes serán perdidos
typo: *ingresados

2021-09-14 19:51 UTC, Tvergara commented on engines/dynattributes/app/commands/dynattributes/validate_attribute.rb
>      return 'value must match with type' unless @data['value'].nil? || validate_value_type
Creo que no te entendí, si `@data['required']` es `false`, toda la expresión `@data['value'].nil? && @data['required']` va a ser falsa y no debería saltar ese error o no? Al menos en consola me está andando bien esa validación

2021-09-14 19:52 UTC, Tvergara commented on app/javascript/components/organizations/configuration.vue
> +            :attr="attr"
Totalmente innecesario jajaj, estaba basandome en el video de CRUD de memo, que él hizo eso para ejemplificar que se podían hacer en hashes los props. Ahora lo quito

2021-09-14 20:01 UTC, Tvergara commented on app/javascript/components/organizations/attribute-form-modal.vue
> +                  </option>
Para poner un placeholder en el select, esa es la mejor forma que encontré, pero si hay alguna mejor la cambio al toque

2021-09-14 20:24 UTC, Tvergara commented
> Algunos detalles chicos. Y otro comentario: por ahora está bien como está, pero después quizás les convenga sacar el botón que abre un modal del componente mismo del modal. Esto porque puede pasar que tengas más de un lugar que active un modal, y quieras que el botón se vea distinto en ambos lugares (por ejemplo, botón de eliminar como parte de las acciones de cada fila de una tabla o como acción en el show de un elemento). Para eso tendrías que manejar el estado de abierto/cerrado con props/eventos

Perfecto, me base de otros modales ya hechos dentro del proyecto, si eventualmente tenemos que cambiarlo los cambiamos todos!

2021-09-14 20:46 UTC, difernandez requested changes

2021-09-14 20:46 UTC, difernandez commented on app/javascript/components/organizations/configuration.vue
> +              v-for="attr in this.attributes"
en el template debería ir sin el this

2021-09-15 17:30 UTC, difernandez approved these changes

2021-09-15 17:42 UTC, merged