Feat/join and leave team
platanus/lacatan pull request #31
Opened 2021-09-15 20:29 UTC by castrocami

### Contexto
​​Reconstruyendo Lakatan. En este [pitch](https://www.notion.so/platanus/Interfaz-de-equipos-v2-0-5d5e4babe8bc437c94e5a181a188f6de) que corresponde a la creación de una forma en que los integrantes de una organización puedan entrar y salirse de un equipo y además de llevar registro de los miembros de los equipos
### Qué se esta haciendo
-Crear botón que permite al usuario unirse o salir de un team
-Crear un shared modal de confirmación de eliminación​

#### En particular hay que revisar
​

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)
<img width="234" alt="Captura de Pantalla 2021-09-15 a la(s) 5 28 40 p  m" src="https://user-images.githubusercontent.com/69872162/133504809-7c97d843-5f8b-44c5-a29e-88a58c432555.png">

<img width="415" alt="Captura de Pantalla 2021-09-15 a la(s) 5 29 02 p  m" src="https://user-images.githubusercontent.com/69872162/133504855-4759f704-ccf0-41f8-bcf3-f79a4cd2bc13.png">

2021-09-16 11:57 UTC, castrocami commented
![](https://github.trello.services/images/mini-trello-icon.png) [Crear botón de unirme/salirme del equipo](https://trello.com/c/hlEyzxlt/38-crear-bot%C3%B3n-de-unirme-salirme-del-equipo)

2021-09-16 13:10 UTC, pfarellano requested changes
En general está súper !!! Que bueno que hiciste el refactor para reutilizar el confirmation-modal !! creo que vas súper. Te dejé un par de dudas y sugerencias, cualquier cosa me puedes preguntar 😉

2021-09-16 13:10 UTC, pfarellano commented on app/javascript/components/teams/team-details.vue
> +    joinLeaveTeam() {
Yo separaría esta función en 2, una que sea `joinTeam` que se llame en el else de la función `handleJoinLeaveClick()` y otra `leaveTeam` que se llame cuando hagan confirmation en el modal

2021-09-16 13:10 UTC, pfarellano commented on app/javascript/components/teams/team-delete-modal.vue
> +      :loading="loading"
Que buen refactor ! 🎉

2021-09-16 13:10 UTC, pfarellano commented on app/javascript/components/teams/team-delete-modal.vue
> +    </confirmation-modal>
Me queda una duda, que es si ya cambiaste en el archivo team-details, el confirmation-modal por este nuevo team-delete-modal ? o eso lo tienes pensado para otro pr ?

2021-09-20 12:00 UTC, castrocami commented on app/javascript/components/teams/team-delete-modal.vue
> +    </confirmation-modal>
Estaba ocupando dentro de team-delete-modal  el confirmation modal para que quedara mas separado

2021-09-20 13:30 UTC, castrocami commented on app/javascript/components/teams/team-details.vue
> +      const newMembersIds = this.teamData.users.map(user => user.id);
Listo! Tengo la duda de esta línea que repito más abajo en el código pero creo que no sé si vale la pena meterlas en una función porque se ve limpio a mi parecer, que crees?

2021-09-20 16:16 UTC, pfarellano approved these changes
ahí siii ! 🚀  súper

2021-09-20 16:22 UTC, merged