Feat/raffles UI
platanus/lacatan pull request #67
Opened 2021-12-14 16:12 UTC by rieg-ec

### Contexto

Falta implementar la funcionalidad de los sorteos. En un [pr](https://github.com/platanus/lacatan/pull/59) anterior se implementó parte de la vista del show de teams, en la mayoria componentes que hacian falta.
 ​
### Qué se hizo

En este pr se implementa la ui restante para los sorteos (solo ui) y se migra a un diseño mobile y con el uso de i18n.
​
### Qué queda por hacer

Quedaria implementar la logica de los sorteos en el front y back, y en arreglar el modal que en vistas mobile no se ve bien.
​

-----------
## Info Adicional (pantallazos, links, fuentes, etc.)

### Mobile:

![Screen Shot 2021-12-14 at 13 06 55](https://user-images.githubusercontent.com/58893812/146035113-fed5aa70-e2c4-4489-b20b-90513829426f.png)

https://user-images.githubusercontent.com/58893812/146035425-7f2fb814-530d-41f9-adb1-d488044943c7.mov

### Desktop:

![Screen Shot 2021-12-14 at 13 09 32](https://user-images.githubusercontent.com/58893812/146035522-cf0dcdd8-221b-4877-a3ac-fb0cda246227.png)

https://user-images.githubusercontent.com/58893812/146036086-65262595-33fc-4514-b9ba-8f1650548e45.mov

2021-12-14 16:14 UTC, monkeyci commented on engines/tasks/app/controllers/tasks/api/v1/definitions_controller.rb
> +                             'INNER JOIN team_responsibilities ON tasks_definitions.team_responsibility_id = team_responsibilities.id
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Layout/LineLength: Line is too long. [133/100]

2021-12-14 16:14 UTC, monkeyci commented on engines/tasks/app/serializers/tasks/api/v1/base_serializer.rb
> +  def nested_resource(resources, namespace = "Tasks::Api::V1")
⚠️ **[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Lint/DuplicateMethods: Method Tasks::Api::V1::BaseSerializer#nested_resource is defined at both engines/tasks/app/serializers/tasks/api/v1/base_serializer.rb:4 and engines/tasks/app/serializers/tasks/api/v1/base_serializer.rb:8.

2021-12-14 16:14 UTC, monkeyci commented on engines/tasks/app/serializers/tasks/api/v1/definition_serializer.rb
> +      nested_resources(object.team_responsibility.team.team_members, namespace = nil)
⚠️ **[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Lint/UselessAssignment: Useless assignment to variable - namespace.

2021-12-14 16:14 UTC, monkeyci commented on engines/tasks/app/serializers/tasks/base_serializer.rb
> +  def nested_resource(resources, namespace = "Tasks")
⚠️ **[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Lint/DuplicateMethods: Method Tasks::BaseSerializer#nested_resource is defined at both engines/tasks/app/serializers/tasks/base_serializer.rb:4 and engines/tasks/app/serializers/tasks/base_serializer.rb:8.

2021-12-14 16:14 UTC, monkeyci commented on app/javascript/api/team-responsibilities.js
> +  update(teamId, teamResponsibilityId) {
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'teamId' is defined but never used                no-unused-vars

2021-12-14 16:14 UTC, monkeyci commented on app/javascript/api/team-responsibilities.js
> +  update(teamId, teamResponsibilityId) {
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'teamResponsibilityId' is defined but never used  no-unused-vars

2021-12-14 16:14 UTC, monkeyci commented on app/javascript/api/team-responsibilities.js
> +  delete(teamId, teamResponsibilityId) {
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'teamId' is defined but never used                no-unused-vars

2021-12-14 16:14 UTC, monkeyci commented on app/javascript/api/team-responsibilities.js
> +  delete(teamId, teamResponsibilityId) {
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'teamResponsibilityId' is defined but never used  no-unused-vars

2021-12-14 16:14 UTC, monkeyci commented on app/javascript/components/shared/three-dot-dropdown.vue
> +            offset: [40, 10],
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>No magic number: 40  no-magic-numbers

2021-12-14 16:14 UTC, monkeyci commented on app/javascript/components/shared/three-dot-dropdown.vue
> +            offset: [40, 10],
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>No magic number: 10  no-magic-numbers

2021-12-14 16:14 UTC, monkeyci commented on app/javascript/components/teams/team-join-leave-btn.vue
> +        alert(e);
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert  no-alert

2021-12-14 16:14 UTC, monkeyci commented on app/javascript/components/teams/team-join-leave-btn.vue
> +        alert(e);
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert  no-alert

2021-12-14 16:14 UTC, monkeyci commented on app/javascript/components/teams/team-responsibilities.vue
> +      alert(e);
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert              no-alert

2021-12-14 16:14 UTC, monkeyci commented on app/javascript/components/teams/team-responsibilities.vue
> +      console.log('join resp');
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement  no-console

2021-12-14 16:14 UTC, monkeyci commented on app/javascript/components/teams/team-responsibilities.vue
> +      console.log('raffle');
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement  no-console

2021-12-14 16:41 UTC, rieg-ec commented on engines/tasks/app/serializers/tasks/api/v1/definition_serializer.rb
> +      nested_resources(object.team_responsibility.team.team_members, namespace = nil)
no es useless :C

2021-12-14 16:46 UTC, monkeyci commented on engines/tasks/app/controllers/tasks/api/v1/definitions_controller.rb
> +      .joins('INNER JOIN team_responsibilities
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/MultilineMethodCallIndentation: Align .joins with Tasks::Definition on line 13.

2021-12-14 16:46 UTC, monkeyci commented on engines/tasks/app/controllers/tasks/api/v1/definitions_controller.rb
> +      .where('teams.id = ?', params[:team_id])
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/MultilineMethodCallIndentation: Align .where with Tasks::Definition on line 13.

2021-12-14 16:46 UTC, monkeyci commented on engines/tasks/app/controllers/tasks/api/v1/definitions_controller.rb
> +      .includes(team_responsibility: { team: { team_members: :user } })
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/MultilineMethodCallIndentation: Align .includes with Tasks::Definition on line 13.

2021-12-14 16:46 UTC, monkeyci commented on app/javascript/components/teams/team-responsibilities.vue
> +      alert(e);
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert  no-alert

2021-12-14 16:49 UTC, rieg-ec commented on engines/tasks/app/controllers/tasks/api/v1/definitions_controller.rb
> +      .joins('INNER JOIN team_responsibilities
se queja por line too long si hago eso, se ve mas bonito asi encuentro yo (?

2021-12-14 18:19 UTC, iaacosta requested changes
Buena! Está bacán el PR, te dejé un mix de comentarios entre chicos/medianos + de estilo/funcionales, avísame si tienes duda con cualquiera!

2021-12-14 18:19 UTC, iaacosta commented on app/javascript/components/teams/team-links.vue
> +    window.addEventListener('resize', () => {
Acá te faltó el `event` o no?

```suggestion
    window.addEventListener('resize', (event) => {
```

Me parece que te funciona porque aún está vigente [el `Window.event`](https://developer.mozilla.org/en-US/docs/Web/API/Window/event), que es global y es el evento del `listener` actual, pero puede estar deprecado en ciertos navegadores

2021-12-14 18:19 UTC, iaacosta commented on app/javascript/components/teams/team-members.vue
> +          :src="require(`../../../assets/images/icons/${icon}`)"
Ídem lo de los _assets_ acá!

```suggestion
          :src="require(`assets/images/icons/${icon}`)"
```

2021-12-14 18:19 UTC, iaacosta commented on app/javascript/components/teams/team-responsibilities.vue
> +          :icon-classes="'w-4 h-4'"
Acá hay varios `v-bind` que te puedes ahorrar tb!

```suggestion
          hierarchy="secondary"
          icon-file-name="plus.svg"
          :icon-only="true"
          icon-classes="w-4 h-4"
```

2021-12-14 18:19 UTC, iaacosta commented on app/javascript/components/teams/team-responsibilities.vue
> +              />
Ídem lo de los `v-bind`:

```suggestion
            <team-members-circles
              :members="responsibility.attributes.teamMembers"
              text-classes="font-medium"
              :text="false"
            />
            <div class="flex flex-row text-xs space-x-2 sm:text-sm">
              <btn
                @click="raffle"
                hierarchy="yellow"
                icon-file-name="ticket.svg"
              >
                <span>{{ $t('raffles.raffle') }}</span>
              </btn>
              <btn
                @click="joinResponsibility"
                hierarchy="green"
                icon-file-name="join.svg"
              >
                <span>{{ $t('raffles.join') }}</span>
              </btn>
            </div>
            <div class="flex-row hidden sm:flex space-x-2">
              <btn
                hierarchy="red"
                :icon-only="true"
                icon-file-name="thrash.svg"
                icon-classes="w-5 h-5"
              />
              <btn
                hierarchy="secondary"
                :icon-only="true"
                icon-file-name="edit.svg"
                icon-classes="w-5 h-5 fill-current"
              />
```

2021-12-14 18:19 UTC, iaacosta commented on app/javascript/locales/es.js
> +        'Esta acción es irreversible y todos las tareas asociadas serán eliminadas.',
```suggestion
        'Esta acción es irreversible y todas las tareas asociadas serán eliminadas.',
```

2021-12-14 18:37 UTC, rieg-ec commented on engines/tasks/app/serializers/tasks/api/v1/definition_serializer.rb
> +      nested_resources(object.team_responsibility.team.team_members, namespace = nil)
ahh cierto, no se me ocurrió pasar `nil` nomás

2021-12-18 22:57 UTC, rieg-ec commented on engines/tasks/app/controllers/tasks/api/v1/definitions_controller.rb
> +  end
nop jeje

2021-12-18 23:00 UTC, rieg-ec commented on spec/controllers/teams_controller_spec.rb
> +  end
nunca me quedó claro si eso se testea o no en los controladores (ni tampoco qué se testea exactamente en un controlador ademas del response code jajaja), esa linea en particular seria buena idea testearla con un shared example e incluirlo en todos los tests de controlador, o hay algo mejor?

2021-12-18 23:41 UTC, rieg-ec commented on app/javascript/components/teams/team-links.vue
> +      ],
cierto

2021-12-18 23:41 UTC, rieg-ec commented on app/javascript/components/teams/team-links.vue
> +    window.addEventListener('resize', () => {
en efecto jaja

2021-12-18 23:42 UTC, rieg-ec commented on app/javascript/components/teams/team-links.vue
> +      // eslint-disable-next-line no-magic-numbers
debo haber tenido uno antes y se me fue sacar la linea XD

2021-12-18 23:48 UTC, rieg-ec commented on app/javascript/locales/es.js
> +        'Esta acción es irreversible y todos las tareas asociadas serán eliminadas.',
buena!

2021-12-19 01:08 UTC, rieg-ec commented on spec/controllers/teams_controller_spec.rb
> +  end
pd: por ahora lo dejé dentro del test del controlador, pero habria que hacer lo mismo para todos los otros tests de controladores que faltan de alguna forma jajaja

2021-12-19 01:08 UTC, monkeyci commented on spec/controllers/teams_controller_spec.rb
> +      it { expect(response).to have_http_status(302) }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/Rails/HttpStatus: Prefer :found over 302 to describe HTTP status code.

2021-12-19 01:08 UTC, monkeyci commented on spec/controllers/teams_controller_spec.rb
> +      it { expect(response).to have_http_status(302) }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/Rails/HttpStatus: Prefer :found over 302 to describe HTTP status code.

2021-12-19 14:20 UTC, iaacosta commented on spec/controllers/teams_controller_spec.rb
> +  end
[alerta de :mucho-texto:]

Yo generalmente a los controladores testeo que:

- Retorne los _response codes_ que espero (incluyendo `unauthorized`)
- Me retorne el/los elemento/s que espero (esto puede ser más overkill)

Para el segundo punto, te puede pasar harto que tienes una policy metida de por medio (`authorize` o `policy_scope`) y en realidad no tiene sentido testear los casos borde de eso acá, porque deberías testearlo en los tests de policy.

Entonces, para el controlador te queda hacer el stub del comportamiento de esos métodos externos e ir testeando los casos. [Acá](https://platanus.slack.com/archives/C01CEGVK0AY/p1632229387048100) hay un buen hilo de ejemplo para el `authorize`, y debería ser similar para el `policy_scope`

-----------------------

Está buena la idea del shared example! Y hay harto donde explorar y probar. Por ejemplo, el `:not_found` viene de [un _concern_ de Power Api](https://github.com/platanus/power_api/blob/5f2b3198352e3ac1e8174abd40fb159c91c5ddab/app/controllers/concerns/api/error.rb#L13-L16) luego de levantar el error de `ActiveRecord::RecordNotFound` (generalmente hecho a través de un `find` o un `find_by!`). Esto igual se repite para otros errores.

Me imagino, para el caso de autenticación, algo como esto:

```ruby
RSpec.shared_examples 'an authenticatable controller action' do
  let(:params) { nil }

  def do_request
    send(method, action, format: :json, params: params)
  end

  context 'when user is signed in' do
    let(:user) { create(:user) }

    before do
      sign_in(user)
      do_request
    end

    it "responds with #{expected_successful_status} status" do
      expect(response).to have_http_status(expected_successful_status)
    end
  end

  context 'when user is not signed in' do
    before { do_request }

    it 'responds with unauthorized status' do
      expect(response).to have_http_status(:unauthorized)
    end
  end
end
```

Y para usarlo:

```ruby
  describe '#index' do
    it_behaves_like 'an authenticatable controller action' do
      let(:method) { :get }
      let(:action) { :index }
      let(:expected_successful_status) { :ok }
    end
  end

  describe '#show' do

    it_behaves_like 'an authenticatable controller action' do
      let(:method) { :get }
      let(:action) { :index }
      let(:expected_successful_status) { :ok }
      let(params) { { id: create(:team).id } }
    end
  end
```

Quizás si uno define la función dentro del bloque del `it_behaves_like`, se pueden ahorrar esos tres `let`s (`method`, `action`, `params`)? Nunca he probado si una función pasa al _scope_ del `shared_example`, pero algo de esa línea estaría buenísimo para evitar tanto copy paste.

No creo que sea necesario ahora, pero si para un refactor general de tests si es que ninguno se hace cargo de esto.

2021-12-20 13:44 UTC, rieg-ec commented on spec/controllers/teams_controller_spec.rb
> +  end
buena! te pasaste, me quedó super claro 🥩  👏

2021-12-21 19:54 UTC, iaacosta approved these changes
✅

2021-12-22 18:42 UTC, aaguilarg approved these changes

2021-12-22 18:47 UTC, merged