Feat/raffles controller index
platanus/lacatan pull request #69
Opened 2021-12-17 19:40 UTC by nicolasguridi

### Contexto
Se están migrando las integraciones del Lacatan viejo al nuevo. Una de ellas es Zapier, que se usa para los sorteos de las tareas.

Zapier tiene _triggers_ y acciones. Se necesitaba agregar el _trigger_ New Raffle, que se usa para saber si ha habido un nuevo _raffle_ asociado a una tarea.
​
### Qué se está haciendo
- Se crea la acción `index` en el `raffles_controller`, que retorna todos los _raffles_ de la tarea por la cual se está consultando
- Se agrega la ruta correspondiente
- Además, se agrega la posibilidad de pasar más información sobre la tarea (más que solo su id), dependiendo de si se pasa el parámetro `deep`
​
#### En particular hay que revisar
​

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

2021-12-17 19:41 UTC, monkeyci commented on engines/tasks/app/controllers/tasks/api/bearers/v1/raffles_controller.rb
> +    respond_with raffles, deep: params[:deep].present?
<sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Not covered lines: 3

2021-12-17 19:41 UTC, monkeyci commented on engines/tasks/app/controllers/tasks/api/bearers/v1/raffles_controller.rb
> +    @raffles ||= tasks_definition.requests
<sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Not covered lines: 15

2021-12-23 00:30 UTC, ldlsegovia requested changes
una cosita

2021-12-23 00:30 UTC, ldlsegovia commented on engines/tasks/app/serializers/tasks/api/bearers/v1/request_serializer.rb
> +      serializer = Api::Bearers::V1::DefinitionSerializer.new(task)
por qué necesitás el serializer si al final haces uso del objeto? Si entiendo bien, esto sería el equivalente:

```ruby
      {
        id: task.id,
        description: task.team_responsibility.description,
        random_assignation: task.random_assignation,
        required_assignations: task.required_assignations
      }
```

no?

2021-12-23 12:17 UTC, nicolasguridi commented on engines/tasks/app/serializers/tasks/api/bearers/v1/request_serializer.rb
> +      serializer = Api::Bearers::V1::DefinitionSerializer.new(task)
Toda la razón, no lo necesito

2021-12-23 12:19 UTC, ldlsegovia commented on engines/tasks/app/controllers/tasks/api/bearers/v1/raffles_controller.rb
> +    respond_with raffles, deep: params[:deep].present?
@nicolasguridi pregunta: este mensaje te apareció porque no habías hecho test del index y luego lo agregaste? para cachar si está funcionando bien

2021-12-23 12:20 UTC, ldlsegovia commented on engines/tasks/app/controllers/tasks/api/bearers/v1/raffles_controller.rb
> +    respond_with raffles, deep: params[:deep].present?
![image](https://user-images.githubusercontent.com/3026413/147239746-b83844d0-df35-4312-ba95-8b47e6b5c47d.png)

Ah, sí. Lo agregaste al final. Success mujaajjaa

2021-12-23 12:20 UTC, nicolasguridi commented on engines/tasks/app/controllers/tasks/api/bearers/v1/raffles_controller.rb
> +    respond_with raffles, deep: params[:deep].present?
Sí! eso mismo jaja está funcionando bien

2021-12-23 12:21 UTC, ldlsegovia commented on engines/tasks/app/controllers/tasks/api/bearers/v1/raffles_controller.rb
> +    respond_with raffles, deep: params[:deep].present?
Me dan ganas de llorar que haya funcionado y que hayas agregado el test jajaja

2021-12-23 12:21 UTC, nicolasguridi commented on engines/tasks/app/controllers/tasks/api/bearers/v1/raffles_controller.rb
> +    respond_with raffles, deep: params[:deep].present?
Por qué? Jajajaj no es así como debería ser?

2021-12-23 12:23 UTC, nicolasguridi commented on engines/tasks/app/controllers/tasks/api/bearers/v1/raffles_controller.rb
> +    respond_with raffles, deep: params[:deep].present?
O te emociona que el mono nos fomente exitosamente las buenas prácticas

2021-12-23 12:23 UTC, ldlsegovia commented on engines/tasks/app/controllers/tasks/api/bearers/v1/raffles_controller.rb
> +    respond_with raffles, deep: params[:deep].present?
ah, sorry. Es llanto de felicidad :) Pasa que hice esto: https://github.com/platanus/simplecov_linter_formatter y https://github.com/platanus/simplecov_text_formatter para lograr lo que acaba de ocurrir pero no lo había visto en acción. Sos el caso de éxito! jaja

2021-12-23 12:26 UTC, nicolasguridi commented on engines/tasks/app/controllers/tasks/api/bearers/v1/raffles_controller.rb
> +    respond_with raffles, deep: params[:deep].present?
Está muy bueno! jajaja

2021-12-23 12:28 UTC, ldlsegovia approved these changes

2021-12-23 12:32 UTC, merged