Feat/roles
platanus/lacatan pull request #71
Opened 2021-12-22 12:44 UTC by Nyveon

### Contexto
Se está desarrollando [este pitch](https://www.notion.so/platanus/Roles-ed73da8d03b0450d846a27b06b185631)
Con fines de implementar roles al modelo de usuarios de Lakatan.

### Qué se esta haciendo
​Instalando Rolify, y implementándolo al modelo.

#### En particular hay que revisar
​¿Estilo en role.rb? Estos archivos se agregaron automáticamente, pero a rubocop parece no gustarle.

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)
Aquí se puede notar que se puede revisar la pertenencia a un rol, y modificar esa pertenencia y que tenga efectos en la base de datos.
![image](https://user-images.githubusercontent.com/54124297/147094658-77ca1c06-6f12-40bc-8bb2-d53250f6199f.png)

2021-12-22 12:45 UTC, monkeyci commented on app/models/role.rb
> +  has_and_belongs_to_many :users, :join_table => :users_roles
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/HasAndBelongsToMany: Prefer has_many :through to has_and_belongs_to_many.

2021-12-22 12:45 UTC, monkeyci commented on app/models/role.rb
> +  has_and_belongs_to_many :users, :join_table => :users_roles
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Style/HashSyntax: Use the new Ruby 1.9 hash syntax.

2021-12-22 12:45 UTC, monkeyci commented on app/models/role.rb
> +             :polymorphic => true,
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Style/HashSyntax: Use the new Ruby 1.9 hash syntax.

2021-12-22 12:45 UTC, monkeyci commented on app/models/role.rb
> +             :optional => true
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Style/HashSyntax: Use the new Ruby 1.9 hash syntax.

2021-12-22 12:45 UTC, monkeyci commented on app/models/role.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/EmptyLines: Extra blank line detected.

2021-12-22 12:45 UTC, monkeyci commented on app/models/role.rb
> +            :inclusion => { :in => Rolify.resource_types },
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Style/HashSyntax: Use the new Ruby 1.9 hash syntax.

2021-12-22 12:45 UTC, monkeyci commented on app/models/role.rb
> +            :inclusion => { :in => Rolify.resource_types },
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Style/HashSyntax: Use the new Ruby 1.9 hash syntax.

2021-12-22 12:45 UTC, monkeyci commented on app/models/role.rb
> +            :allow_nil => true
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Style/HashSyntax: Use the new Ruby 1.9 hash syntax.

2021-12-22 12:45 UTC, monkeyci commented on config/initializers/rolify.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/TrailingWhitespace: Trailing whitespace detected.

2021-12-22 12:45 UTC, monkeyci commented on spec/factories/roles.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/TrailingWhitespace: Trailing whitespace detected.

2021-12-22 19:26 UTC, difernandez requested changes
Se ve bien! Pido cambios por las cosas de estilo no más. Aunque sean cosas autogeneradas, la idea es que idealmente quede todo lo agregado según las reglas de estilo. Dejé un comentario sobre lo que me parece es una excepción igual, faltaría agregar ahí el disable

2021-12-22 19:26 UTC, difernandez commented on app/models/role.rb
> +  has_and_belongs_to_many :users, :join_table => :users_roles
por lo general estoy de acuerdo con esta recomendación del mono de usar through en vez de HABTM, pero en este caso creo que puede haber una excepción, por se autogenerado y porque quizás se necesita un cambio en la gema ([hay un PR abierto de hace muucho tiempo](https://github.com/RolifyCommunity/rolify/pull/181)). Eso si, agregaría el `rubocop:disable` para esta regla a esta línea para que no moleste el linter

2021-12-23 14:25 UTC, difernandez approved these changes

2021-12-23 14:38 UTC, merged