Feat/api documentation
platanus/lacatan pull request #74
Opened 2021-12-30 14:22 UTC by tamaralues

### Contexto
Se está implementando el diseño de figma del nuevo lacatan.

### Qué se esta haciendo
​En este pr se esta haciendo el traspaso de la documentación de los endpoints de lacatan. Esto se acceden en la vista de API keys en la pestaña de enpoints. Para ver el ejemplo hay que hacer click en el icono de ayuda.

#### En particular hay que revisar
​Hay que revisar el archivo endpoint-example-modal, organization-key, endpoint card y se hicieron unos cambios chicos en el botón y en el modal.

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

![Untitled](https://user-images.githubusercontent.com/29900907/147759789-21fd78fe-8283-460a-9ffb-4dc91e5d65b0.gif)

2022-01-03 21:14 UTC, flouMicaza requested changes
Dejé un mini comentario

2022-01-03 21:14 UTC, flouMicaza commented on app/javascript/components/organizations/endpoint-example-modal.vue
> +    this.curl = commandArgs.join(' ');
Quizás esto que está en el `mounted` lo dejaría en un método aparte porque en el mounted se podrían querer hacer otras cosas después. Y como esto tiene pinta de llamada a una api en verdad lo sacaría a otro archivo, pero como es de ejemplo quizás no es tan necesario.

2022-01-03 21:20 UTC, tamaralues commented on app/javascript/components/organizations/endpoint-example-modal.vue
> +    this.curl = commandArgs.join(' ');
A nono no ess, esque es un json que esta en el proyecto, que se "arma" según esas condiciones para mostrar la syntax curl del endpoint.

2022-01-04 18:26 UTC, flouMicaza approved these changes
:100:

2022-01-04 19:37 UTC, merged