feat(user invitations): add invitations model
platanus/lacatan pull request #83
Opened 2022-01-07 20:45 UTC by CarloGauss33

### Contexto
Se requiere una forma de verificar si un usuario ha recibido o no alguna invitacion correspondiente a integraciones existentes.​
### Qué se esta haciendo
Se genera migracion para modelo de invitaciones

#### En particular hay que revisar
Migracion, modelo y tests​
-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

2022-01-07 20:53 UTC, aaguilarg requested changes
Te dejo una duda 👀

2022-01-07 20:53 UTC, aaguilarg commented on db/schema.rb
> +
y esta tabla? habias hecho una migracion antes? de ser asi se te quedo esta sin hacer rollback

2022-01-07 20:57 UTC, CarloGauss33 commented on db/schema.rb
> +
Si, no me habia dado cuenta que quedo en el schema. Ahora le hice el rollback

2022-01-07 21:02 UTC, aaguilarg reviewed
Lo veo bien! una cosa chica nomas

2022-01-07 21:02 UTC, aaguilarg commented on spec/factories/invitations.rb
> +    user { nil }
le dejaria `user` (i.e: sin el `{ nil }`)

2022-01-10 20:07 UTC, aaguilarg approved these changes

2022-01-10 20:08 UTC, merged