Feat/create raffle action
platanus/lacatan pull request #87
Opened 2022-01-14 18:31 UTC by nicolasguridi

### Contexto
​En el Lacatan nuevo hay una vista de equipos con las responsabilidades de este. Para cada responsabilidad, había un botón para sortear que no hacía nada. Se necesitaba que al apretar el botón se ejecutara el sorteo y se mostraran los resultados de este.

### Qué se esta haciendo
- Se crea un nuevo controlador para la api de las `Tasks::Requests`, con la acción `create`.
- Se incluyen tests para el nuevo controlador y un serializador para las requests.
- Se crea el endpoint `createRaffle` en la api `requests`.
- Se hace un modal para crear y mostrar los resultados de un sorteo.
- Se usa el nuevo modal en el componente `team-responsibilities` de la vista de [equipos.](url) Además, ahora cada `team-responsibility` del equipo tiene su propio componente.
​
#### En particular hay que revisar
​

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

https://user-images.githubusercontent.com/42162243/149566639-b0eb632b-e1a3-4f8c-beda-bf5723a4a653.mov

Al final se ve que las imágenes de perfil aparecen en blanco. Eso es un bug que se arregló localmente en [este PR](https://github.com/platanus/lacatan/pull/82), por lo que queda pendiente hacer un componente "profile-picture" con el arreglo para usarlo en todo el proyecto sin problemas. Pediré agregarlo como tarjeta de mejora continua.

2022-01-14 18:32 UTC, nicolasguridi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ejecutar sorteo](https://trello.com/c/fSAvXjSS/84-ejecutar-sorteo)

2022-01-17 14:25 UTC, difernandez requested changes

2022-01-17 14:25 UTC, difernandez commented on engines/tasks/config/routes.rb
>        end
- Encuentro un poco raro definir el parámetro `id` con un `scope`, creo que en este caso es porque también está definido el `team_id` a partir de un scope. Creo que trataría de usar `resources` siempre que se pueda para no tener que indicar los ids y cada request CRUD a mano. En este caso como venía de antes no es necesario cambiarlo, pero por si sirve, creo que esto sería algo así:

```
resources :teams, only: [] do
  resources :tasks, controller: 'definitions', only: [:index] do
    resources :requests, only: [:create]
  end
end
```
- Además de lo anterior, en este caso creo que no es necesario que la nueva ruta de requests esté nesteada dentro de los teams, e ideal si se requiere solo la info necesaria. Me refiero a que la ruta podría ser `/api/v1/tasks/${taskId}/requests`, en el controller no se usa el `team_id`. No estoy seguro, pero quizás se puede lograr eso en el ejemplo anterior usando [shallow nesting](https://guides.rubyonrails.org/routing.html#shallow-nesting) en el `resources :teams`, si no habría que hacerlo a mano

2022-01-17 14:25 UTC, difernandez commented on app/javascript/components/teams/create-raffle-modal.vue
> +      type: Boolean,
comentario muy toc: mantendría consistencia en el orden, que vaya `type` primero

2022-01-17 14:25 UTC, difernandez commented on app/javascript/components/teams/team-responsibilities.vue
> +      v-if="!this.loading"
venía de antes, pero se pasó el `this` acá

2022-01-17 14:25 UTC, difernandez commented on app/javascript/components/teams/team-responsibility-card.vue
> +      taskId: this.responsibility.id,
como este `taskId` no se modifica y solo se pasa como prop a otro componente, calza un poco más con un computed (o se podría pasar el `responsibility.id` directo en el template tambn)

2022-01-20 17:54 UTC, nicolasguridi commented on engines/tasks/config/routes.rb
>        end
Gracias por los comentarios! quedó mucho mejor como tú dices

2022-01-20 19:13 UTC, difernandez approved these changes

2022-01-20 19:14 UTC, merged