Refactor/profile picture component
platanus/lacatan pull request #89
Opened 2022-01-14 20:26 UTC by nicolasguridi

### Contexto
​En Lakatan nuevo, las fotos de perfil del usuario se estaban poniendo como elementos img html, por lo que no estaban estandarizadas, por lo que cualquier cambio había que hacerlo en todas las partes del proyecto que mostraran la foto de perfil.
### Qué se esta haciendo
- Se crea el componente global `profile-picture`. Incluye la opción de mostrar un tooltip con el nombre del usuario.
- Se reemplazan todas las fotos de perfil con este componente
​
#### En particular hay que revisar
​

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

https://user-images.githubusercontent.com/42162243/149580475-7addc360-b3f6-49d3-9648-7f8ee26502fe.mov

2022-01-14 20:34 UTC, nicolasguridi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Componente foto de perfil](https://trello.com/c/cQ3NTSbZ/116-componente-foto-de-perfil)

2022-01-17 12:36 UTC, rieg-ec requested changes
Buena! bacan que hayas estandarizado eso jeje

te deje un comentario corto

2022-01-17 12:36 UTC, rieg-ec commented on app/javascript/components/shared/profile-picture.vue
> +      return this.tooltip ? 'bg-white px-2 py-1 shadow rounded-xl bg-opacity-90 shadow-xl' : 'hidden';
```suggestion
      return this.tooltip ? 'bg-white px-2 py-1 rounded-xl bg-opacity-90 shadow-xl' : 'hidden';
```

2022-01-17 12:36 UTC, rieg-ec commented on app/javascript/components/profile/edit.vue
> +      return `${this.firstName} ${this.lastName}`;
el user deberia tener el metodo `name` que es para el nombre completo creo

2022-01-19 19:28 UTC, rieg-ec approved these changes
buena 👍 !

2022-01-19 19:29 UTC, merged

2022-01-27 20:29 UTC, FloValdes commented
![](https://github.trello.services/images/mini-trello-icon.png) [Poder unir a un usuario a distintos proyectos a través de llamadas a la api](https://trello.com/c/lWEnPbWv/121-poder-unir-a-un-usuario-a-distintos-proyectos-a-trav%C3%A9s-de-llamadas-a-la-api)