Feat/axios api
platanus/lacatan pull request #9
Opened 2021-08-13 21:00 UTC by castrocami

### Contexto
Reconstruyendo Lakatan. [En este pitch](https://www.notion.so/platanus/Interfaz-de-equipos-v1-0-1c4cd55247ce4ec5b0d94dad66cc294a), que corresponde a CRUDs de equipos
​
### Qué se esta haciendo
- Crear metodos para hacer display de teams consumiendo teams api
- Se eliminó el display de teams mediante json
​
#### En particular hay que revisar
​

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

2021-08-13 21:43 UTC, aaguilarg approved these changes

2021-08-13 21:43 UTC, aaguilarg commented on app/javascript/api/index.js
> +);
Borremos esto mejor

2021-08-13 21:43 UTC, aaguilarg commented on app/javascript/api/teams.js
> +export default getTeams;
Se ve bien, eso si un detalle. Como vamos a seguir metiendo metodos acá, dejemos algo asi
```javascript
export default {
  getTeams({ organizationId }) {
    return api({
      method: 'get',
      url: `/api/v1/organizations/${organizationId}/teams`,
  });
};
```

y lo importamos asi 
```javascript
import TeamsApi from 'ruta'
```
y lo usamos asi

```javascript
TeamsApi.getTeams(...)...
```

2021-08-13 21:49 UTC, aaguilarg requested changes
deje unos comentarios para arreglar

2021-08-16 16:31 UTC, monkeyci commented on app/javascript/components/teams/teams.vue
> +      {{team.attributes.name}}
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 space after '{{', but not found   vue/mustache-interpolation-spacing

2021-08-16 16:31 UTC, monkeyci commented on app/javascript/components/teams/teams.vue
> +      {{team.attributes.name}}
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 space before '}}', but not found  vue/mustache-interpolation-spacing

2021-08-16 16:31 UTC, monkeyci commented on app/javascript/components/teams/teams.vue
> +import TeamsApi from '../../api/teams';
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Trailing spaces not allowed                  no-trailing-spaces

2021-08-16 16:31 UTC, monkeyci commented on app/javascript/components/teams/teams.vue
> +  data(){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before opening brace           space-before-blocks

2021-08-16 16:31 UTC, monkeyci commented on app/javascript/components/teams/teams.vue
> +    return{
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Expected space(s) after "return"             keyword-spacing

2021-08-16 16:31 UTC, monkeyci commented on app/javascript/components/teams/teams.vue
> +    }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing semicolon                            semi

2021-08-16 16:31 UTC, monkeyci commented on app/javascript/components/teams/teams.vue
> +    TeamsApi.getTeams({ organizationId: this.organization.id }).then((response)=>{
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before =>                      arrow-spacing

2021-08-16 16:31 UTC, monkeyci commented on app/javascript/components/teams/teams.vue
> +    TeamsApi.getTeams({ organizationId: this.organization.id }).then((response)=>{
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space after =>                       arrow-spacing

2021-08-16 16:31 UTC, monkeyci commented on app/javascript/components/teams/teams.vue
> +    }).catch((error)=>{
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before =>                      arrow-spacing

2021-08-16 16:31 UTC, monkeyci commented on app/javascript/components/teams/teams.vue
> +    }).catch((error)=>{
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space after =>                       arrow-spacing

2021-08-16 16:31 UTC, monkeyci commented on app/javascript/components/teams/teams.vue
> +      console.error('Error obtaining teams from api', error)
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement                 no-console

2021-08-16 16:31 UTC, monkeyci commented on app/javascript/components/teams/teams.vue
> +      console.error('Error obtaining teams from api', error)
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing semicolon                            semi

2021-08-16 16:31 UTC, monkeyci commented on app/javascript/components/teams/teams.vue
> +    });
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Trailing spaces not allowed                  no-trailing-spaces

2021-08-16 16:31 UTC, monkeyci commented on app/javascript/components/teams/teams.vue
> +  }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing trailing comma                       comma-dangle

2021-08-16 16:39 UTC, aaguilarg approved these changes

2021-08-16 16:39 UTC, merged