Feat/harvest reality
platanus/lacatan pull request #91
Opened 2022-01-18 18:44 UTC by FloValdes

### Contexto
Siguiendo [este pitch](https://www.notion.so/platanus/Reality-Harvest-20c9ba3637ca4ccdbc9c3ac25e6276bf) se busca hacer una integración de Harvest con lacatan, permitiendo invitar y archivar usuarios a Harvest desde la página.
​
### Qué se esta haciendo
En este primer PR se creó la engine Harvestation, la que será la encargada de contener las funciones necesarias para la integración, se integró esta engine con la app principal, se creó un cliente que se comunica con la API de Harvest, un servicio que llama a este cliente y finalmente un controlador para llamar estas integraciones desde la página.
​
#### En particular hay que revisar
​- Definición de la engine
- Integración de engine con app principal
- Servicio
- Cliente
- Controlador

2022-01-18 18:45 UTC, monkeyci commented on engines/harvestation/lib/harvestation/extensions.rb
> +# On /home/florencia/Platanus/lacatan/engines/harvestation/app/extensions/harvestation/my_model_ext.rb you need to add:
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Layout/LineLength: Line is too long. [119/100]

2022-01-18 18:45 UTC, monkeyci commented on engines/harvestation/lib/harvestation/extensions.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/TrailingEmptyLines: 2 trailing blank lines detected.

2022-01-18 18:45 UTC, monkeyci commented on spec/engines/harvestation/controllers/harvestation/api/v1/harvest_users_controller_spec.rb
> +      is_expected.to have_http_status(:created)
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/ImplicitSubject: Don't use implicit subject.

2022-01-18 18:45 UTC, monkeyci commented on spec/engines/harvestation/controllers/harvestation/api/v1/harvest_users_controller_spec.rb
> +      is_expected.to have_http_status(:no_content)
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/ImplicitSubject: Don't use implicit subject.

2022-01-18 18:45 UTC, monkeyci commented on spec/engines/harvestation/services/harvestation/harvest_service_spec.rb
> +  let (:user) { create(:user, organization: organization, email: 'a@email.com', first_name: 'nombre', last_name: 'apellido') }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/LineLength: Line is too long. [126/100]

2022-01-18 18:45 UTC, monkeyci commented on spec/engines/harvestation/services/harvestation/harvest_service_spec.rb
> +      expect(client).to have_received(:create_user).with(organization.id, user.email, user.first_name, user.last_name)
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/LineLength: Line is too long. [118/100]

2022-01-18 18:45 UTC, monkeyci commented on engines/harvestation/app/assets/config/harvestation_manifest.js
> +//= link_directory ../stylesheets/harvestation .css
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected space or tab after '//' in comment  spaced-comment

2022-01-18 18:46 UTC, monkeyci commented on engines/harvestation/app/controllers/harvestation/api/v1/harvest_users_controller.rb
> +    respond_with(harvest_service.user_list)
<sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Not covered lines: 3

2022-01-18 18:46 UTC, monkeyci commented on engines/harvestation/app/services/harvestation/harvest_service.rb
> +      client.get_users
<sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Not covered lines: 4

2022-01-18 21:30 UTC, AndresGarciadelaHuerta requested changes
Lo veo súper bien! 💯  Está ordenado el código y los commits, un agrado de revisar 👌 

Dejé varios comentarios/preguntas y algunos cambios, dime nomás qué opinas

2022-01-18 21:30 UTC, AndresGarciadelaHuerta commented on Gemfile.lock
> +  remote: engines/githubify
por qué se agregó esto al `Gemfile.lock` si la gema ya estaba en el `Gemfile` desde antes 🤔 ?

2022-01-18 21:30 UTC, AndresGarciadelaHuerta commented on engines/harvestation/app/clients/harvestation/harvest_user_client.rb
> +    BASE_URL ||= "https://api.harvestapp.com/v2"
creo que debería ir como variable de entorno o no? qué opinas?

2022-01-18 21:30 UTC, AndresGarciadelaHuerta commented on engines/harvestation/app/controllers/harvestation/api/v1/harvest_users_controller.rb
> +  def archive_user
creo que tanto `create_user` y al `archive_user` los dejaría como `create` y `archive`, dado que el contexto lo entrega el nombre del controller `HarvestUser`. Qué opinas? También lo cambiaría en los tests.

2022-01-18 21:30 UTC, AndresGarciadelaHuerta commented on engines/harvestation/config/routes.rb
> +      patch '/harvest/archive_user' => 'harvest_users#archive_user'
ídem

2022-01-18 21:30 UTC, AndresGarciadelaHuerta commented on engines/harvestation/app/services/harvestation/harvest_service.rb
> +      harvest_id = harvest_id(user.email)
si se guardara el `harvest_id` dentro del modelo `User` creo que sería más simple de entender esta lógica 🤔

2022-01-18 21:30 UTC, AndresGarciadelaHuerta commented on engines/harvestation/app/clients/harvestation/harvest_user_client.rb
> +  class HarvestUserClient
me queda la duda de si el nombre debiera incluir la palabra `User` o no. En un futuro puede que se agreguen cosas no directamente relacionadas a los usuarios?

2022-01-19 12:52 UTC, aaguilarg commented on engines/harvestation/app/controllers/harvestation/api/v1/harvest_users_controller.rb
> +  def archive_user
me sumo a lo de andrés, que una sola acotación. Los dejaría como `create` y `update`, mas REST

2022-01-19 12:52 UTC, aaguilarg commented on app/controllers/api/v1/organization_configurations_controller.rb
> +
no es necesario que lo hagas ahora right now, viene asi de antes. Pero creo que seria super bueno refactorear este codigo para que no crezca infinito este metodo, algo como
```ruby
def permitted params
  ...
  add_slackgration_params
  add_githubify_params
  add_harvestation_params
end

private

## definir los metodos
```

2022-01-19 12:52 UTC, aaguilarg commented on engines/harvestation/app/clients/harvestation/harvest_user_client.rb
> +      user_list = get_users
like it, buscaria en bdd primero y si no esta definido, buscarlo y persistirlo

2022-01-19 12:52 UTC, aaguilarg commented on engines/harvestation/app/clients/harvestation/harvest_user_client.rb
> +    BASE_URL ||= "https://api.harvestapp.com/v2"
+1

2022-01-19 12:52 UTC, aaguilarg commented on engines/harvestation/app/clients/harvestation/harvest_user_client.rb
> +  class HarvestUserClient
Es posible 🤔  
Harvest tiene mas endpoints que usuarios que quizá se podrian usar a futuro

2022-01-19 13:00 UTC, FloValdes commented on engines/harvestation/app/clients/harvestation/harvest_user_client.rb
> +  class HarvestUserClient
para este mismo pitch se necesitan usar los endpoints de proyectos (como listar proyectos, asociar usuarios a un proyecto) por eso pensaba hacer un HarvestProjectClient

2022-01-19 13:51 UTC, aaguilarg commented on engines/harvestation/app/clients/harvestation/harvest_user_client.rb
> +  class HarvestUserClient
🤔  que será mejor? De repente preguntar en techi-banana, es una respuesta que puede ayudarles a varios

2022-01-19 13:56 UTC, AndresGarciadelaHuerta commented on engines/harvestation/app/clients/harvestation/harvest_user_client.rb
> +  class HarvestUserClient
sí, creo que vale la pena preguntar en slack. Personalmente me inclino por un sólo cliente dado que la parte de headers, tokens y definir los tipos de request se van a repetir y sería menos DRY.

2022-01-19 19:57 UTC, monkeyci commented on spec/engines/harvestation/services/harvestation/harvest_service_spec.rb
> +    allow(client).to receive(:create_user).and_return({'id' => '1'})
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/SpaceInsideHashLiteralBraces: Space inside { missing.

2022-01-19 19:57 UTC, monkeyci commented on spec/engines/harvestation/services/harvestation/harvest_service_spec.rb
> +    allow(client).to receive(:create_user).and_return({'id' => '1'})
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/SpaceInsideHashLiteralBraces: Space inside } missing.

2022-01-19 20:11 UTC, AndresGarciadelaHuerta reviewed
Quedó muuy weno 👏  dejé dos dudas chicas. Arreglaría el comentario del mono nomás

2022-01-19 20:11 UTC, AndresGarciadelaHuerta commented on spec/engines/harvestation/controllers/harvestation/api/v1/harvest_users_controller_spec.rb
> +  describe "PATCH #archive" do
acá sería `describe "PATCH #update"`

2022-01-19 20:11 UTC, AndresGarciadelaHuerta commented on engines/harvestation/app/clients/harvestation/harvest_user_client.rb
> +  class HarvestUserClient
misma duda, se va a dejar así al final el nombre?

2022-01-19 20:13 UTC, FloValdes commented on engines/harvestation/app/clients/harvestation/harvest_user_client.rb
> +  class HarvestUserClient
en slack me dijeron que quizás sería mejor dejar una clase base de client que tenga los métodos generales y separar los clientes en dos, pero como al menos hasta ahora solo es un cliente, quizás lo mejor sería dejar ese cambio para cuando sea necesario y por ahora dejar este como HarvestClient 🤔

2022-01-19 20:15 UTC, AndresGarciadelaHuerta commented on engines/harvestation/app/clients/harvestation/harvest_user_client.rb
> +  class HarvestUserClient
okaa, me parece 💯

2022-01-19 21:19 UTC, AndresGarciadelaHuerta approved these changes
💎

2022-01-20 12:44 UTC, aaguilarg requested changes

2022-01-20 13:05 UTC, aaguilarg approved these changes

2022-01-20 13:06 UTC, merged

2022-01-21 13:00 UTC, FloValdes commented
![](https://github.trello.services/images/mini-trello-icon.png) [Crear / archivar usuarios back](https://trello.com/c/nYLSkdWG/119-crear-archivar-usuarios-back)