Feat/harvest add remove front
platanus/lacatan pull request #92
Opened 2022-01-21 14:26 UTC by FloValdes

### Contexto
Siguiendo [este pitch](https://www.notion.so/platanus/Reality-Harvest-20c9ba3637ca4ccdbc9c3ac25e6276bf) lo que se quiere hacer es poder integrar Harvest con Lakatan, permitiendo invitar usuarios, agregarlos a distintos proyectos y archivarlos.
​
### Qué se esta haciendo
Ya se implementó la lógica necesaria en back para agregar y archivar personas, en este PR se implementaron las vistas de front asociadas. Para esto se hizo un refactor de estos botones:
![image](https://user-images.githubusercontent.com/37163115/150535095-16e3388a-f6f3-487e-8a99-97910d25d556.png)
Para aprovechar los elementos en común que tendrán todos los botones de integraciones de servicios.

Lo que se hizo:
`refactor(harvest-controller): remove organization id from params`: se eliminó `organization_id` de los parámetros necesarios para llamar los métodos de Harvest, ya que este atributo se puede sacar del usuario. 

`feat(users-vue): add locals to text`: se agregaron locales a `users.vue`, que no los tenía.

`refactor(integrations-btn): refactor slack button into generic integrations button`: los botones de integración comparten mucha lógica: modales de confirmación para agregar / quitar a alguien, la lógica de cambiar el botón entre agregar / quitar, los estilos y posteriormente el mostrar un modal antes de enviar un request. Toda esta lógica común se implementó en `service-wrapper` y el estilo particular del botón en `user-integration-btn`. Finalmente cada servicio particular implementa un `service-button` (`slack-button`, `harvest-button`, etc.) en donde se definen los métodos particulares de cada servicio: llamadas a la api, modales, etc.

`feat(harvest-btn): add harvest button`: se agrega el `harvest-btn` siguiendo la misma lógica mencionada.
​
#### En particular hay que revisar
​- Métodos cambiados al eliminar organization_id como parámetro para las llamadas a la api.
- Refactor a los botones de servicios.
- Implementación del botón de Harvest.

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

https://user-images.githubusercontent.com/37163115/150536517-19c89a35-cca8-4b65-9f93-6f6459db4d9f.mp4

https://user-images.githubusercontent.com/37163115/150536521-a611a939-e911-47f4-bbbb-ec25640521cd.mp4

2022-01-21 18:34 UTC, FloValdes commented
![](https://github.trello.services/images/mini-trello-icon.png) [Poder invitar o archivar usuarios desde la página](https://trello.com/c/rZz6Ri1v/120-poder-invitar-o-archivar-usuarios-desde-la-p%C3%A1gina)

2022-01-25 12:18 UTC, difernandez requested changes
Está bueno! Dejo algunos comentarios chicos y un comentario opcional sobre los dos componentes de botones de servicio

2022-01-25 13:16 UTC, FloValdes commented on app/javascript/components/user/integrations/user-integration-btn.vue
> +<template>
sí, me parece!

2022-01-25 18:55 UTC, difernandez approved these changes
Like! Un detalle chico no más, pero dejo aprobado

2022-01-25 18:55 UTC, difernandez commented on app/javascript/spec/components/user/integrations/service-integration-btn.spec.js
> +import ServiceWrapper from '../../../../components/user/integrations/service-integration-btn.vue';
Acá faltó cambiar el nombre a `ServiceIntegrationBtn` pa que sea como el archivo

2022-01-26 13:04 UTC, aaguilarg approved these changes

2022-01-26 13:19 UTC, merged